sudo: false
language: go
go:
  - 1.6
  - 1.7
  - tip
install:
  - go get -v github.com/mattn/goveralls
script:
  - go build -v
#  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=cover.out
